CREATE DATABASE IF NOT EXISTS healthcare_db;
USE healthcare_db;
CREATE TABLE IF NOT EXISTS users(id BIGINT PRIMARY KEY AUTO_INCREMENT, username VARCHAR(120), email VARCHAR(255) UNIQUE, password VARCHAR(255), role VARCHAR(20));
CREATE TABLE IF NOT EXISTS doctor(id BIGINT PRIMARY KEY AUTO_INCREMENT, name VARCHAR(120), specialization VARCHAR(120), availability VARCHAR(255));
CREATE TABLE IF NOT EXISTS appointment(id BIGINT PRIMARY KEY AUTO_INCREMENT, date DATETIME, status VARCHAR(30), user_id BIGINT, doctor_id BIGINT, CONSTRAINT fk_user FOREIGN KEY(user_id) REFERENCES users(id), CONSTRAINT fk_doc FOREIGN KEY(doctor_id) REFERENCES doctor(id));
